{% set version = "1.15.0" %}

package:
    name: ecmwf_grib
    version: {{ version }}

source:
    fn: grib_api-{{ version }}.tar.gz
    url: https://software.ecmwf.int/wiki/download/attachments/3473437/grib_api-{{ version }}-Source.tar.gz
    sha256: 733f48e2882141003b83fa165d1ea12cad3c0c56953bc30be1d5d4aa6a0e5913

build:
    number: 1
    skip: True  # [win]
    detect_binary_files_with_prefix: true

requirements:
    build:
        - cmake
        - jasper
        - libpng >=1.6.21,<1.7
        - libnetcdf 4.4.*
        - gcc
        - isl 0.12.*
    run:
        - jasper
        - libpng >=1.6.21,<1.7
        - libnetcdf 4.4.*
        - libgcc
        - isl 0.12.*

test:
    commands:
        - grib_info
        - ls $(grib_info -t)
        - ls $(grib_info -d)
        - test -f ${PREFIX}/lib/libgrib_api.so  # [linux]
        - test -f ${PREFIX}/lib/libgrib_api_f77.so  # [linux]
        - test -f ${PREFIX}/lib/libgrib_api_f90.so  # [linux]
        - test -f ${PREFIX}/lib/libgrib_api.dylib  # [osx]
        - test -f ${PREFIX}/lib/libgrib_api_f77.dylib  # [osx]
        - test -f ${PREFIX}/lib/libgrib_api_f90.dylib  # [osx]
about:
    home: https://software.ecmwf.int/wiki/display/GRIB/Home
    license: Apache-2.0
    summary: The ECMWF API for encoding and decoding WMO FM-92 GRIB edition 1 and edition 2 messages.

extra:
    recipe-maintainers:
        - kmuehlbauer
        - ocefpaf
        - pelson
        - rhattersley
